export enum ACTION {
  ADD_STORY = 'ADD_STORY',
  UPDATE_STORY = 'UPDATE_STORY',
  DELETE_STORY = 'DELETE_STORY',
  ADD_MEMBER = 'ADD_MEMBER',
  REMOVE_MEMBER = 'REMOVE_MEMBER',
  ADD_PAYMENT = 'ADD_PAYMENT',
  UPDATE_PAYMENT = 'UPDATE_PAYMENT',
  REMOVE_PAYMENT = 'REMOVE_PAYMENT',
}
